### ISSUE TITLE
 Create tests for record & replay graphs mechanism

### ISSUE THREAD

**Issue by EwanC** [reble/llvm#15]
Convert existing Codeplay tests for [SYCL_EXT_CODEPLAY_GRAPHS](https://github.com/codeplaysoftware/standards-proposals/pull/135) to llvm-test-suite tests for testing the record & replay graph interface from the [unified oneAPI graphs extension](https://github.com/reble/llvm/pull/4)

**Comment by EwanC** [comment]
We have started looking into this and tests will be in https://github.com/Bensuo/llvm-test-suite initally

**Comment by Bensuo** [comment]
Some record and replay tests are added in this PR https://github.com/Bensuo/llvm-test-suite/pull/1though most are failing due to missing implementation obviously! Once the record and replay functionality is in place they can be finalized.
