### ISSUE TITLE
Implement exceptions for incompatible extensions.

### ISSUE THREAD

**Issue by EwanC** [reble/llvm#154]
We have specified in #138 that we the following exceptions are used with graphs and exception is thrown:
* sycl_ext_oneapi_enqueue_barrier
* sycl_ext_oneapi_memcpy2d
* sycl_ext_codeplay_kernel_fusion
* sycl_ext_oneapi_kernel_properties
* sycl_ext_oneapi_device_global

These exception behaviour needs implemented and tested

**Comment by mfrancepillois** [comment]
PR #276 addresses this issue. https://github.com/reble/llvm/pull/276
