### ISSUE TITLE
Waiting on a queue after graph submission causes incorrect behaviour.

### ISSUE THREAD

**Issue by Bensuo** [reble/llvm#47]
It appears that calling `queue.wait()` after the graph has been submitted causes incorrect behaviour/results in the example code, like so:

```c++
  // Execute several iterations of the graph
  for (unsigned n = 0; n < iterations; n++) {
    testQueue.submit([&](handler &h) { h.exec_graph(graphExec); });
  }
  // Perform a wait on all graph submissions.
  testQueue.wait();
```

In reality this should at the very least do nothing if the graph has already been executed (as happens in the current prototype).

**Comment by EwanC** [comment]
This should be fixed by https://github.com/reble/llvm/pull/190 closing
