### ISSUE TITLE
memcpy operations break on queue with lazy_queue property

### ISSUE THREAD

**Issue by Bensuo** [reble/llvm#48]
Trying to do a memcpy using a queue with the `lazy_queue` property causes program termination with the following error:

```
die: The host-visible proxy event missing
terminate called without an active exception
```

This presents an issue for both example code/test having to manually initialize USM memory and also for future users of a prototype implementation who would likely want to use `memcpy`.

**Comment by EwanC** [comment]
lazy queue property has been removed by #100  so closing issue.
