### ISSUE TITLE
Push common DPC++ changes back to mainline

### ISSUE THREAD

**Issue by EwanC** [reble/llvm#84]
PR https://github.com/reble/llvm/pull/82 touches shared DPC++ code in `sycl/include/sycl/detail/common.hpp`  to enable correct resolution of namespaces when the macros are used in extensions.

This code modification has implications outwith the scope of our extension, so it would be worth pushing it back to the central DPC++ repo as a standalone PR.

**Comment by reble** [comment]
Done https://github.com/intel/llvm/pull/9360
