### ISSUE TITLE
Implement querying the event returned by a graph submission for profiling information

### ISSUE THREAD

**Issue by EwanC** [reble/llvm#96]
Implement the `info::event_profiling` query from an event returned by a graph submission. This implementation should reflect the outcome of https://github.com/reble/llvm/issues/52

**Comment by mfrancepillois** [comment]
This feature is unsupported by DPC++ / level zero backend.
The returned timestamps are the same for all command states (submit, start, end).
We therefore obtain the same result using events returned from graph submissions.
Graph implementation of this feature may be enough, but we need to wait for DPC++ to support profiling feature before checking sycl-graph implementation.

**Comment by mfrancepillois** [comment]
It seems that this feature is now supported for DPC++ level_zero and CUDA backends. 
PR #318 tests the timing info obtained from info::event_profiling query on events returned from the submission of a graph.

**Comment by EwanC** [comment]
Closing, this was merged upstream in https://github.com/intel/llvm/pull/11324
